window.onerror=function(a){alert(a)};function g_e(a){return document.getElementById(a)}animation_done=!0;var Main=function(){this.animations=[];this.tasks=[];this.context={};this.path="";self=this};Main.prototype.start_animating=function(){try{if(animation_done){g_e("input").onkeypress=function(a){return main.key_checker(a)};var a=this.animations.shift();a.func(a.args)}else g_e("input").onkeypress=function(a){if(13==a.keyCode)return g_e("input").value="",!1}}catch(b){}};
Main.prototype.add_animation=function(a,b){this.animations.push({func:a,args:b})};Main.prototype.start_working=function(){try{var a=this.tasks.shift();a.func(a.args)}catch(b){}};Main.prototype.add_task=function(a,b){this.tasks.push({func:a,args:b})};Main.prototype.animation_blink=function(){var a=0;window.setInterval(function(){0==a?(document.getElementById("blinker").innerHTML=">",a=1):1==a&&(document.getElementById("blinker").innerHTML="&nbsp;",a=0)},1E3)};
Main.prototype.animation_fade=function(a){animation_done=!1;var b=0,c=0;g_e(a.element).style.display="block";var d=setInterval(function(){g_e(a.element).style.opacity=b;1<b&&0==c?c=1:0>b?(animation_done=!0,c=0,g_e(a.element).style.display="none",clearInterval(d)):0==c?b+=.2:1==c&&(b-=.2)},500)};
Main.prototype.plbl=function(a){animation_done=!1;var b=document.getElementById(a.element),c=0,d=setInterval(function(){c<=a.message.length?("|"==a.message.charAt(c)?b.innerHTML+="<br>":"^"!=a.message.charAt(c)&&(b.innerHTML+=a.message.charAt(c)),c++):(animation_done=!0,clearInterval(d))},a.speed)};
Main.prototype.animation_reboot=function(a){self.add_animation(self.clear_console,{});self.add_animation(self.animation_fade,{element:"startUp"});self.add_animation(self.plbl,{message:"initiliazing boot sequence............|reticulating squids....^^^^^^|dereticulating squids....^^^^^^|deregulating squids....^^^^^^|reregulating squids....^^^^^^|squids prepared...^^^^^^",element:"console",speed:75});self.add_animation(self.clear_console);self.add_animation(self.plbl,{message:"SquidOS.^^^^^^.^^^^^^.^^^^^^ Booted!^^^^^^^^^^^^^^",
element:"console",speed:75});self.add_animation(self.clear_console,{});self.add_animation(self.plbl,{message:"Awating command. Type help for a list of commands.",speed:75,element:"console"})};
Main.prototype.command=function(a){"y"!=a||this.context.started||(this.add_animation(this.animation_reboot,{}),this.context.started=!0);"help"==a&&(this.context.first_reboot?this.context.first_reboot&&(this.add_animation(this.clear_console,{}),this.add_animation(this.plbl,{element:"console",speed:75,message:"Ok^^^^^^^^^^^^^| Here goes second try..."})):(this.add_animation(this.clear_console,{}),this.add_animation(this.plbl,{element:"console",message:"List of avialable commands : ^^^^^^^^^^^^^^^||...||^^^^Well, hold on a second^^^^^|| Well this engine is incapable of percise seconds so give me say.^^^^.^^^^.^^^^ presicely 975 miliseconds to work this out.|||^^^^^^^^^^^^^Ok! We've gotten somewhere! | I just figured out something crucial to the playing of this game. Currently there aren't any commands to display! ^^^^^^^ Wait. ^^^^^^^ That can't be right.|| ^^^^^^^ Maybe turning it on and off again will fix this...",
speed:75}),this.add_animation(this.animation_reboot,{}),this.context.first_reboot=!0))};Main.prototype.get_input=function(){var a=g_e("input").value;g_e("input").value="";return a};Main.prototype.clear_console=function(a){g_e("console").innerHTML=""};Main.prototype.key_checker=function(a){if(13==a.keyCode)return this.command(this.get_input()),!1};Main.prototype.start=function(){var a=this;setInterval(function(){a.start_working()},1);setInterval(function(){a.start_animating()},1);this.animation_blink()};
alert("compiled");main=new Main;main.start();
